### ISSUE TITLE
 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [yausername/youtubedl-android#234] opened 2023-05-09 10:22 UTC
When using gradle 8.0.0 or above, release will catch directly, debug will not have problems

`                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at c7.e.b(SourceFile:1)
                                                                                                    	at c7.h0.b(SourceFile:554)
                                                                                                    	at c7.h0.<init>(SourceFile:164)
                                                                                                    	at y4.o9.a(SourceFile:8)
                                                                                                    	at com.yausername.youtubedl_android.YoutubeDL.initPython(SourceFile:46)
                                                                                                    	at com.yausername.youtubedl_android.YoutubeDL.init(SourceFile:205)
                                                                                                    	at w2.g.j(SourceFile:10)
                                                                                                    	at f6.a.n(SourceFile:9)
                                                                                                    	at t6.c0.run(SourceFile:111)`

**Comment by JunkFood02** [comment] 2023-05-09 12:09
duplicate of #71

**Closed by JunkFood02** 2023-05-09 12:09 UTC

**Comment by AndroidJohnsonWang** [comment] 2023-05-10 01:23
@JunkFood02 Written proguard rule is still catch

**Comment by AndroidJohnsonWang** [comment] 2023-05-10 01:25
` java.lang.ExceptionInInitializerError
                                                                                                    	at a7.e.b(SourceFile:1)
                                                                                                    	at a7.l0.b(SourceFile:399)
                                                                                                    	at a7.l0.<init>(SourceFile:68)
                                                                                                    	at com.yausername.youtubedl_common.utils.ZipUtils.unzip(SourceFile:1)
                                                                                                    	at com.yausername.youtubedl_android.YoutubeDL.initPython(SourceFile:48)
                                                                                                    	at com.yausername.youtubedl_android.YoutubeDL.init(SourceFile:205)`

**Comment by AndroidJohnsonWang** [comment] 2023-05-10 03:52
add -keepattributes SourceFile in proguard.fix bug.
