### ISSUE TITLE
Is it works when App released on Google Play?

### ISSUE THREAD

**Issue by fangyuxi** [yausername/youtubedl-android#119] opened 2021-11-22 08:06 UTC
Is it works when App released on Google Play?
Can someone tell me about it?
We want to use this to develop a music app.
Thank you, everyone.

**Comment by xibr** [comment] 2021-11-22 14:14
duplicate of [#88](https://github.com/yausername/youtubedl-android/issues/88)

**Closed** 2021-11-24 23:33 UTC
