### ISSUE TITLE
YoutubeDLException:ERROR:HOP-HP-Hp1nhok: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by muhammad-hamza-shahid** [yausername/youtubedl-android#90] opened 2020-12-21 07:38 UTC
YoutubeDLException:ERROR:HOP-HP-Hp1nhok: YouTube said: Unable to extract video data
This is the error which can to my screen the app was working fine but after a few days it starts failing command and when I viewed the error in Logcat this is what it shows.
are there any changes in youtube policy ? or is there any update in your repo policy.
Also, I want to publish my app to the play store for free using this repository so am I allowed to do so. 
Thanks.

**Comment by xibr** [comment] 2020-12-22 04:38
this error caused by youtube-dl binary, make sure you're using latest version of youtube-dl binary.

> Also, I want to publish my app to the play store for free using this repository so am I allowed to do so.

Putting this app on the google play store is a violation of their terms.

**Comment by xibr** [comment] 2021-04-30 21:58
No answer so I'm closing. Please feel free to open a new issue if you find another bug.

**Closed by xibr** 2021-04-30 21:58 UTC
