### ISSUE TITLE
Inquiry about APK file size when building

### ISSUE THREAD

**Issue by yyms3275** [yausername/youtubedl-android#126] opened 2021-12-14 07:54 UTC
The APK file size is too large at build time.
I have to subtract ffmpeg, but it reduces to some extent.
Is there any way to reduce the build size by including ffmpeg?

* With FFMPEG: 90 MB
* Without FFMPEG : 30MB

**Comment by xibr** [comment] 2021-12-14 08:12
Duplicate of #51

You can use abi splits to reduce apk size.

**Comment by xibr** [comment] 2021-12-14 10:30
Run ffmpeg commands not supported yet.

**Comment by yyms3275** [comment] 2021-12-15 03:40
Thanks for the active reply.

**Closed** 2021-12-15 03:39 UTC
