### ISSUE TITLE
Library doesn't work?!

### ISSUE THREAD

**Issue by LSDsl** [yausername/youtubedl-android#96] opened 2021-02-05 12:56 UTC
I tested example and it doesn't work

```
2021-02-05 15:54:08.191 21162-21162/com.yausername.youtubedl_android_example E/StreamingExample: failed to get stream info
    com.yausername.youtubedl_android.YoutubeDLException: /data/app/com.yausername.youtubedl_android_example-2/lib/x86/libpython.bin.so: can't open file '/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/__main__.py': [Errno 2] No such file or directory
    
        at com.yausername.youtubedl_android.YoutubeDL.execute(YoutubeDL.java:201)
        at com.yausername.youtubedl_android.YoutubeDL.getInfo(YoutubeDL.java:129)
        at com.yausername.youtubedl_android_example.StreamingExampleActivity.lambda$startStream$0(StreamingExampleActivity.java:91)
        at com.yausername.youtubedl_android_example.-$$Lambda$StreamingExampleActivity$S_IPZokIU_Ah9xWdWn4vfaRICHE.call(lambda)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by 86x** [comment] 2021-03-10 11:06
The example app seems to be working fine.
I was able to reproduce the error you got by entering a URL that is not supported by youtube-dl. 

In my test I've went to "Streaming example" exactly as you did and then entered "https://aaa.bbb" as a url and tried to stream that. I then got a _E/StreamingExample: failed to get stream info_ as well.

Currently, it seems to me as if you tried to download a url that is not supported by youtube-dl. 
1. Could you provide further details on what you've tried to download? (Maybe you've also pasted a seemingly valid url but somehow managed to start or end that with a space or any other character?)
2. Did you try updating the youtube-dl binary manually from the example app?

**Comment by xibr** [comment] 2021-06-13 19:28
No answer so I'm closing. Please feel free to open a new issue if you find another bug.

**Closed by xibr** 2021-06-13 19:28 UTC
