### ISSUE TITLE
Stream load speed inquiry

### ISSUE THREAD

**Issue by yyms3275** [yausername/youtubedl-android#167] opened 2022-07-05 15:26 UTC
There is a delay of a few seconds when loading streaming.  Can't it be loaded a little faster?

It takes about 5-6 seconds to play.

ex : https://youtu.be/p2fxv3PAtLU

**Comment by xibr** [comment] 2022-07-05 16:53
it's a known issue, however it's a duplicate of #11

**Closed by xibr** 2022-07-05 16:53 UTC
